# Generated by Django 4.2.15 on 2024-08-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(db_column='blog_ID', primary_key=True, serialize=False)),
                ('blog_text', models.TextField()),
            ],
            options={
                'db_table': 'blogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(db_column='restaurant_ID', primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_address', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('review_crawling_check', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(db_column='review_ID', primary_key=True, serialize=False)),
                ('review_title', models.CharField(max_length=2048)),
                ('review_link', models.TextField()),
                ('review_description', models.TextField()),
                ('blog_crawling_check', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
    ]
